FROM openjdk:21-jdk-slim

# Install Gradle.
ENV GRADLE_VERSION 8.9
RUN curl -L https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -o /tmp/gradle.zip \
    && unzip /tmp/gradle.zip -d /opt/ \
    && rm /tmp/gradle.zip

ENV PATH="/opt/gradle-${GRADLE_VERSION}/bin:${PATH}"

RUN gradle --version