FROM openjdk:21-jdk-slim

ENV SONAR_SCANNER_VERSION 4.8.0.2856
RUN curl -o /tmp/sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_SCANNER_VERSION}.zip \
    && unzip /tmp/sonarscanner.zip -d /opt/ \
    && rm /tmp/sonarscanner.zip

ENV PATH="/opt/sonar-scanner-${SONAR_SCANNER_VERSION}/bin:${PATH}"

RUN sonar-scanner --version