# Use the Alpine Linux base image.
FROM alpine:latest

RUN apt-get update && apt-get install -y curl unzip
# Install python3, py3-pip (needed for AWS CLI), and jq.
# The AWS CLI will be installed via pip.
RUN apk add --no-cache python3 py3-pip jq

# Install the official AWS CLI via pip.
RUN pip3 install awscli