name: Docker Image Maker
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:

  build-docker-awscli-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_awscli
          push: true
          tags: |
            ghcr.io/${{ vars.GIT_REPO }}/docker-awscli-image:${{ github.sha }}
            ghcr.io/${{ vars.GIT_REPO }}/docker-awscli-image:latest

  build-gradle-image:
    runs-on: ubuntu-latest
    needs: build-docker-awscli-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Gradle Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_gradle
          push: true
          tags: |
            ghcr.io/${{ vars.GIT_REPO }}/gradle-custom-image:${{ github.sha }}
            ghcr.io/${{ vars.GIT_REPO }}/gradle-custom-image:latest

  build-alpine-image:
    runs-on: ubuntu-latest
    needs: build-gradle-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Alpine Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: |
            ghcr.io/${{ vars.GIT_REPO }}/alpine-awscli-image:${{ github.sha }}
            ghcr.io/${{ vars.GIT_REPO }}/alpine-awscli-image:latest

#  build-windows-image:
#    runs-on: windows-latest # Use a Windows runner for this job
#    needs: build-alpine-image
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub (or other registry)
#        # For Windows, Docker Hub is often a better choice
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and Push Windows Image
#        run: |
#          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/windows-msbuild-image:${{ github.sha }}
#          docker push ${{ secrets.DOCKERHUB_USERNAME }}/windows-msbuild-image:${{ github.sha }}
#        working-directory: ./windows-msbuild-image # Set working directory for the commands


  build-sonarscanner-image:
    runs-on: ubuntu-latest
    needs: build-alpine-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push SonarScanner Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile_sonar_scanner
          push: true
          tags: |
            ghcr.io/${{ vars.GIT_REPO }}/sonarscanner-image:${{ github.sha }}
            ghcr.io/${{ vars.GIT_REPO }}/sonarscanner-image:latest
