name: Spring Boot CI/CD With Gradle
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/gradle_build_app.yml
          
  call-test-suite:
    needs: build
    uses: ./.github/workflows/test-suite.yml
          
  deploy:
    runs-on: ubuntu-latest
    needs: call-test-suite
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: .
      - name: Deploy the application
        run: |
          echo "Downloaded artifact from the 'build' job..."
          echo "Deploying the artifact: spring-boot-app"
