name: Build and Test
on:
  push:
    branches:
      - main

jobs:
    build_java:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'
          - name: Grant execute permission to gradlew
            run: chmod +x gradlew
          - name: Build with Gradle
            run: ./gradlew build
          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
                name: java-app
                path: build/libs/*.jar
    test_java:
        needs: build_java
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'
              cache: 'gradle'
          - name: Grant execute permission to gradlew
            run: chmod +x gradlew
          - name: Run tests with Gradle
            run: ./gradlew test
