name: Containerized Application CI/CD
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
permissions:
  contents: read
  packages: write
jobs:
  build-and-push-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Build Environment
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Custom Runner Image
        id: image_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ vars.GIT_REPO }}/custom-java-runner:${{ github.sha }}
            ghcr.io/${{ vars.GIT_REPO }}/custom-java-runner:latest